Stock analytics
adobecom/stock pull request #47
Opened 2023-03-02 23:19 UTC by So1ene

Stock analytics

Test urls:

Authors block
https://stock-analytics--stock--webistry-development.hlx.page/docs/authoring/blocks/authors
`<div class="authors" daa-im="true" daa-lh="authors">`

Banner block
https://stock-analytics--stock--webistry-development.hlx.page/docs/authoring/blocks/banner
`<div class="banner large light" daa-im="true" daa-lh="banner|large|light">`

Featured columns block
https://stock-analytics--stock--webistry-development.hlx.page/docs/authoring/blocks/featured-columns
`<div class="featured-columns" daa-im="true" daa-lh="featured-columns">`

Image carousel block
https://stock-analytics--stock--webistry-development.hlx.page/docs/authoring/blocks/image-carousel
`<div class="image-carousel" daa-im="true" daa-lh="image-carousel">`

Image Rows block
https://stock-analytics--stock--webistry-development.hlx.page/docs/authoring/blocks/image-rows
`<div class="image-rows" daa-im="true" daa-lh="image-rows">`

In-article-cta block
https://stock-analytics--stock--webistry-development.hlx.page/docs/authoring/blocks/in-article-cta
`<div class="in-article-cta content" daa-im="true" daa-lh="in-article-cta">`

Page-feed block
https://stock-analytics--stock--webistry-development.hlx.page/docs/authoring/blocks/page-feed
`<div class="page-feed col-3-pf-cards" daa-im="true" daa-lh="page-feed">`

Video course block
https://stock-analytics--stock--webistry-development.hlx.page/docs/authoring/blocks/course
`<div class="course" daa-im="true" daa-lh="course">`

Separator block
[(this block is only being used in the homepage, so there is no block-sample page for it)](https://stock-analytics--stock--webistry-development.hlx.page/pages/artisthub/)
`<div class="separator" daa-im="true" daa-lh="separator">`

2023-03-08 17:09 UTC, chrischrischris approved these changes

2023-03-14 17:17 UTC, merged

2023-03-14 17:22 UTC, chrischrischris requested changes

2023-03-15 19:26 UTC, So1ene commented on pages/scripts/utils.js
> +      window.scroll({ top: toggleSection.offsetTop - 97, left: 0, behavior: 'smooth' });
Addressed in https://github.com/adobecom/stock/pull/51

2023-03-15 19:27 UTC, So1ene commented on pages/scripts/utils.js
> +export const { createTag } = await import(`${miloLibs}/utils/utils.js`);
Addressed in https://github.com/adobecom/stock/pull/51

2023-03-15 19:27 UTC, So1ene commented on pages/blocks/anchor-section/anchor-section.js
> +      window.scroll({ top: section.offsetTop - 97, left: 0, behavior: 'smooth', });
Addressed in https://github.com/adobecom/stock/pull/51